---
title: "Un cours sur les indices des prix"
author: "Steve Martin"
date: "été 2020"
documentclass: article
geometry: margin=1in
site: bookdown::bookdown_site
description: "Une introduction moderne et simple aux indices des prix"
github-repo: "ppd-dpp/cours-indices-des-prix"
bibliography: "references.bib"
---

# Aperçu{-}

Ce cours donne une introduction moderne et simple aux indices des prix. L'accent mis sur les principales idées et concepts qui sont importants pour les utilisateurs et les compilateurs d'indices de prix; par conséquent, le cours n'est pas encyclopédique et plusieurs sujets importants sont soit traités rapidement, soit pas du tout traités. De nombreuses références sont fournies pour compléter le matériel de ce cours et étendre la portée des sujets traités. Dans l'ensemble, le cours repose fermement sur le domaine de la théorie et est conçu pour aider à favoriser la compréhension de ce qu'est un indice des prix. Plusieurs exemples pratiques utilisant le langage de programmation R sont donnés tout au long du cours, ainsi que plusieurs exercices appliqués. Mais la plupart des aspects les plus «réels» de l'élaboration d'un indice des prix sont ignorés. Ce n'est pas parce que ces choses ne sont pas importantes; il est plutôt difficile d'apprécier ces sujets plus pratiques sans une solide compréhension de la théorie.

Le cours est divisé en quatre modules qui s'appuient les uns sur les autres. Le premier module donne une introduction aux indices de prix, en se concentrant principalement sur les aspects informatiques d'un indice de prix. Le deuxième module donne une large introduction à la théorie des indices des prix, en mettant l'accent sur la motivation des indices des prix qui sont produits par les organismes statistiques nationaux. Le troisième module couvre les ajustements de qualité, l'un des principaux obstacles pratiques lors de la construction d'un indice des prix. Le quatrième module rassemble le tout avec un exercice étendu pour construire et analyser un indice des prix avec R.

Tous les modules ne sont pas nécessaires pour comprendre les indices de prix, et le matériel de ce cours peut être utilisé par des apprenants ayant une variété de parcours et d'objectifs. Dans tous les cas, le premier module devrait être le point de départ, car il fournit une introduction de base sans approfondir la théorie mathématique.

Ceux qui s'intéressent principalement aux aspects de calcul d'un indice de prix peuvent suivre le module 4 après le module 1, en sautant le matériel plus théorique des modules 2 et 3. Cette séquence est appropriée pour les personnes ayant peu ou pas de connaissances préalables en économie ou en statistique, et qui le font pas besoin d'utiliser un indice des prix pour le travail d'analyse.

Ceux qui ont déjà été familiarisés avec la théorie économique peuvent suivre le module 2 après le module 1 pour acquérir une compréhension plus approfondie du matériel du module 1, suivi du module 4 pour mettre ces idées en pratique. Cette séquence est appropriée pour ceux qui utilisent des indices de prix pour le travail analytique.

Les personnes ayant déjà été exposées à l'économétrie et aux statistiques peuvent suivre le module 3 après le module 2 pour en savoir plus sur certains défis pratiques lors de la construction d'un indice de prix, suivi à nouveau par le module 4. Cette séquence est appropriée pour ceux qui utilisent et construisent des indices de prix, car elle donne les outils fondamentaux nécessaires pour concevoir un indice des prix.